In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [59]:
texts = pd.read_csv('scipop4.csv', encoding = 'utf-8') #пока наилучший вариант был с третьей итерацией

In [41]:
texts = texts.drop(['Unnamed: 0'], axis=1)

In [42]:
train, test = train_test_split(texts, test_size=0.3)

In [43]:
y_train = train['class'] 
y_test = test['class']

In [44]:
#train

In [45]:
import ksslib.readability_metrics as kk

In [46]:
def statist_vectors(text):
    FRE = kk.flesch_RE(text)
    FKG = kk.flesch_kincaid_grade(text)
    SMOG = kk.smog_index(text)
    CLI = kk.coleman_liau_index(text)
    DCH = kk.dale_chall_score(text)
    GF = kk.gunning_fog(text)
    return [FRE, FKG, SMOG, CLI, DCH, GF]

In [47]:
#try_me = statist_vectors(train['text'][1])

In [48]:
#try_me

In [49]:
def count_me_all(texts):
    return [statist_vectors(text) for text in texts]

In [50]:
x_train = count_me_all(train['text'])
x_test = count_me_all(test['text'])

In [64]:
train

text  class
147  Если смотреть на первые элементы последователь...      2
79   Lockheed Martin Американская компания Lockheed...      1
156  На протяжении 150 лет знаменитый центр Брока р...      2
255              Ученые из МГТУ имениБаумана совмес...      3
76   Терракотовая статуя из мавзолея императора Цин...      1
211  Астрономы из МГУ исследовали как излучается ве...      3
233  Компания Nikon более известна своими любительс...      3
171  В ближайшее время разработчики намерены миниат...      2
20   Часто приходится слышать, что, живи дельфины н...      1
37   Физики из Массачусетского университета разрабо...      1
82   Aquila Facebook Американская компания Facebook...      1
106                Руины города Таква  Фото: Wikime...      1
158  Кардиомиоцит, флуоресцентная микроскопия. Cred...      2
81   МС-21-300 «Иркут» Подмосковный Центральный аэр...      1
226  Как вещество, содержащееся в пиве или паутине,...      3
14   Жизнь клетки насыщена событиями не меньше, чем...      1
135   У физики — невероятная биография. В ней можно...      2
212  Сотрудники Центрального аэрогидродинамического...      3
114  Большой подземный ксеноновый детектор незафикс...      2
190              Ученые из Уппсальского университет...      2
24   Изначально ученые расшифровывали геном, чтобы ...      1
210  Палеонтологи обнаружили отпечатки родственника...      3
204              Исследователи с некоторым удивлени...      2
101              В журнале PLOS ONE  выпускаемом ме...      1
122  Бытовая мудрость гласит, что все тайное станов...      2
197              В конце января команда охотников з...      2
95               В традиционных культурах существую...      1
238  Диатомовая земля, которая используется для ста...      3
229  О льде, который вовсе не лед, о частицах, кото...      3
75   Премьер-министр Сингапура Ли Сянь Лун Wikimedi...      1
..                                                 ...    ...
46   Сегодня хочется рассказать сказочную историю п...      1
121  Магматические породы, найденные в Коста-Рике, ...      2
26   Всегда приятно найти в Москве неизведанное при...      1
222  Несколько дней назад специалисты Аризонского у...      3
29   Киберпанк снова в моде. В этом году должна вый...      1
64   Яндекс.Диктовка в Google Play Николай Воронцов...      1
103              Северо-Американское космическое аг...      1
15   Как долго человек может задерживать дыхание, ч...      1
182  Мы публикуем стенограмму лекции главного редак...      2
180  Мы публикуем расшифровку лекции доктора биолог...      2
111  Измеряя температуру атмосферы Юпитера, ученые ...      2
99                             Антонио Келла    Нау...      1
50   В начале апреля британская компания Hybrid Air...      1
12   Московские инженеры создали портативную беспро...      1
19   До середины прошлого века люди надеялись встре...      1
203                        Партнер проекта      Сме...      2
59   Мы, то есть N + 1, продолжаем наш проект «Сдел...      1
249              Группа исследователей Солнца из ун...      3
63   В одной из самых популярных китайских легенд о...      1
42   Veuve Clicqout Cave Privée погружают на 40-лет...      1
88   Мы публикуем полную расшифровку лекции доктора...      1
144  ВМС США объявили о скором завершении программы...      2
127  Эволюцию трудно разглядеть невооруженным глазо...      2
47   Рецензии на «Марсианина» были в чем-то похожи ...      1
133  В научном исследовании, как и в любом другом в...      2
113  Исследователи из нескольких российских институ...      2
143  На прошлой неделе команда «Хаббла» опубликовал...      2
218  Останки мужчины с зажившими переломами нашли п...      3
36   В продолжении статей про солнечную активность ...      1
38   Эта новость прошла мимо Хабра, тем не менее в ...      1

[179 rows x 2 columns]

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
scaler = StandardScaler()
x_fit = scaler.fit(x_train)
x_transform = scaler.transform(x_train)
x_fit_test = scaler.fit(x_test)
x_transform_test = scaler.transform(x_test)

In [54]:
x_transform

array([[ 0.94144548, -0.03752427, -0.21609744, -1.08180242, -0.77547203,
        -0.12556262],
       [-0.61838498,  0.49744557,  0.45623353,  0.82691951,  0.35753456,
         0.33945206],
       [ 0.27952241, -0.24556809,  0.09765701, -0.33184234,  0.14172378,
         0.06044325],
       ...,
       [ 0.3015649 ,  0.17051956,  0.00801288, -0.87593103, -0.43017478,
        -0.03255969],
       [-0.63135115,  2.31039891,  1.62160721, -0.58182904,  0.65966965,
         1.98250393],
       [ 1.0788869 , -0.30500918, -0.66431809, -1.33767116, -1.16393143,
        -0.55957633]])

In [55]:
from sklearn import svm
from sklearn.naive_bayes import MultinomialNB

In [56]:
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier

In [57]:
from sklearn.svm import SVC

model_svc = SVC()
model_svc.fit(x_transform, y_train)
print(model_svc)

expected_svc = y_test
predicted_svc = model_svc.predict(x_transform_test)

print(metrics.classification_report(expected_svc, predicted_svc))
print(metrics.confusion_matrix(expected_svc, predicted_svc))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
             precision    recall  f1-score   support

          1       0.53      0.62      0.57        32
          2       0.55      0.58      0.56        31
          3       0.33      0.14      0.20        14

avg / total       0.50      0.52      0.50        77

[[20  9  3]
 [12 18  1]
 [ 6  6  2]]


In [58]:
model = KNeighborsClassifier()
model.fit(x_transform, y_train)
print(model)

expected = y_test
predicted = model.predict(x_transform_test)

print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
             precision    recall  f1-score   support

          1       0.45      0.53      0.49        32
          2       0.35      0.39      0.37        31
          3       0.40      0.14      0.21        14

avg / total       0.40      0.40      0.39        77

[[17 15  0]
 [16 12  3]
 [ 5  7  2]]


А что если попробовать стандартное преобразование текстов? Традиционно делаем предобработку

In [62]:
def set_clean(s):
    try:
        # print(type(s))
        clean_line = re.sub('[\W\d_-]+', ' ', s.lower().strip())
        return re.sub(' +', ' ', clean_line)
    except AttributeError:
        ''#print ("this was a series")

In [70]:
import re
from sklearn import svm
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords

In [67]:
train_clean = train.applymap(set_clean) #применяем еще раз нашу предобработку
test_clean = test.applymap(set_clean)

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
def tfidf_vec(voc=None):
    if(voc):
        vectorizer = TfidfVectorizer(ngram_range=(1, 1),
                                     stop_words='russian',
                                     min_df=5,   
                                     max_df=0.9)  
        tr = vectorizer.fit_transform(train_clean["text"]) 
        te = vectorizer.fit_transform(test_clean["text"]) 
        return (tr, te)
    else:
        vectorizer = TfidfVectorizer() 
        tr = vectorizer.fit_transform(train_clean["text"]) 
        voc = vectorizer.get_feature_names()
        vectorizer = CountVectorizer(vocabulary=voc) 
        te = vectorizer.fit_transform(test_clean["text"]) 
        return (tr, te)
train_counts, test_counts = tfidf_vec() 

tfidf_transformer = TfidfTransformer()

x_train = tfidf_transformer.fit_transform(train_counts)
x_test = tfidf_transformer.fit_transform(test_counts)

C:\Users\Ksenia\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [72]:
clf = MultinomialNB().fit(x_train, y_train)
predicted = clf.predict(x_test)
len(predicted)

77

In [73]:
print(classification_report(y_pred=predicted, y_true=y_test))

             precision    recall  f1-score   support

          1       0.43      0.94      0.59        32
          2       0.43      0.10      0.16        31
          3       0.00      0.00      0.00        14

avg / total       0.35      0.43      0.31        77



C:\Users\Ksenia\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [74]:
model = KNeighborsClassifier()
model.fit(x_train, y_train)
print(model)

expected = y_test
predicted = model.predict(x_test)

print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
             precision    recall  f1-score   support

          1       0.44      0.84      0.58        32
          2       0.53      0.26      0.35        31
          3       0.00      0.00      0.00        14

avg / total       0.40      0.45      0.38        77

[[27  5  0]
 [22  8  1]
 [12  2  0]]


In [75]:
from sklearn.svm import SVC

model_svc = SVC()
model_svc.fit(x_train, y_train)
print(model_svc)

expected_svc = y_test
predicted_svc = model_svc.predict(x_test)

print(metrics.classification_report(expected_svc, predicted_svc))
print(metrics.confusion_matrix(expected_svc, predicted_svc))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
             precision    recall  f1-score   support

          1       0.42      1.00      0.59        32
          2       0.00      0.00      0.00        31
          3       0.00      0.00      0.00        14

avg / total       0.17      0.42      0.24        77

[[32  0  0]
 [31  0  0]
 [14  0  0]]


C:\Users\Ksenia\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
